MODEL:
  TYPE:  resnet 
  DEPTH: 50
  NUM_CLASSES: 1000
RESNET:
  TRANS_FUN: bottleneck_transform
  NUM_GROUPS: 1
  WIDTH_PER_GROUP: 64
  STRIDE_1X1: False
MOCO:
  ARCH: resnet
  DIM: 128
  K: 65536
  MOMENTUM: 0.999
  TAU: 0.07
  MLP: False
  V2_AUG: False
  COS: False
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 30.0 
  LR_POLICY: steps
  STEPS: [0, 30, 60, 90]
  LR_MULT: 0.1
  MAX_EPOCH: 100 
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0
TRAIN:
  DATASET: imagenet_dpflow
  SPLIT: train
  BATCH_SIZE: 256 
  IM_SIZE: 224
  CHECKPOINT_PERIOD: 25
  EVAL_PERIOD: 1  # do not eval
  FINETUNE: True
TEST:
  DATASET: imagenet_dpflow
  SPLIT: val
  BATCH_SIZE: 256 
  IM_SIZE: 224
NUM_GPUS: 8
USE_DPFLOW: False 
NUM_REPLICAS: 1
DATA_LOADER:
  NUM_WORKERS: 8
CUDNN:
  BENCHMARK: True
OUT_DIR: .
